### ISSUE TITLE
Building is failing after updating Blazor application to dotnet core 3.0 preview 9

### ISSUE THREAD

**Issue by mgochmuradov** [BlazorExtensions/Logging#40]
I have a Blazor application that uses this plugin, and it is stopped building after updating to dotnet core 3.0 preview 9, with following error:
```
Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void Blazor.Extensions.Logging.BrowserConsoleLogger/<Log>d__4`1::MoveNext()' in assembly: 'Blazor.Extensions.Logging.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task`1<!!0> Microsoft.JSInterop.IJSRuntime::InvokeAsync(System.String,System.Object[])
4>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
4>   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
4>   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
4>   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
4>   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
4>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
4>   --- End of inner exception stack trace ---
4>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
4>   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
4>   at Mono.Linker.Steps.MarkStep.Process()
4>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
4>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
4>   at Mono.Linker.Pipeline.Process(LinkContext context)
4>   at Mono.Linker.Driver.Run(ILogger customLogger)
4>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
4>   at Mono.Linker.Driver.Main(String[] args)
4>C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview9.19424.4\targets\Blazor.MonoRuntime.targets(441,5): error MSB3073: The command "dotnet "C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.blazor.mono\3.0.0-preview9.19421.1\build\netstandard1.0\../../tools/illink/illink.dll" -l none --disable-opt unreachablebodies --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.blazor.mono\3.0.0-preview9.19421.1\build\netstandard1.0\../../tools/mono/bcl/" -d "C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.blazor.mono\3.0.0-preview9.19421.1\build\netstandard1.0\../../tools/mono/bcl/Facades/" -o "C:\dev\xxx.WebBlazor\obj\Debug\netstandard2.0\blazor\linker/" -x "C:\dev\xxx.WebBlazor\Linker.xml" -a "C:\Users\xxx\.nuget\packages\blazor.extensions.logging\0.3.0\lib\netstandard2.0\Blazor.Extensions.Logging.JS.dll" -a "C:\Users\xxx\.nuget\packages\blazor.extensions.logging\0.3.0\lib\netstandard2.0\Blazor.Extensions.Logging.dll" -a "C:\Users\xxx\.nuget\packages\devexpress.blazor\0.3.1\lib\netstandard2.0\DevExpress.Blazor.dll" -a "C:\Users\xxx\.nuget\packages\devextreme.aspnet.data\2.2.0\lib\netstandard2.0\DevExtreme.AspNet.Data.dll" -a "C:\Users\xxx\.nuget\packages\identitymodel\3.10.10\lib\netstandard2.0\IdentityModel.dll" -a "C:\Users\merdan\.nuget\packages\microsoft.aspnetcore.authorization\3.0.0-preview9.19424.4\lib\netstandard2.0\Microsoft.AspNetCore.Authorization.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.blazor\3.0.0-preview9.19424.4\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.blazor.httpclient\3.0.0-preview9.19424.4\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.HttpClient.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.components\3.0.0-preview9.19424.4\lib\netstandard2.0\Microsoft.AspNetCore.Components.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.components.forms\3.0.0-preview9.19424.4\lib\netstandard2.0\Microsoft.AspNetCore.Components.Forms.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.components.web\3.0.0-preview9.19424.4\lib\netstandard2.0\Microsoft.AspNetCore.Components.Web.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.metadata\3.0.0-preview9.19424.4\lib\netstandard2.0\Microsoft.AspNetCore.Metadata.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.webutilities\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.WebUtilities.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.bcl.asyncinterfaces\1.0.0-preview9.19421.4\lib\netstandard2.0\Microsoft.Bcl.AsyncInterfaces.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.csharp\4.4.0\lib\netstandard2.0\Microsoft.CSharp.dll" -a "C:\Users\merdan\.nuget\packages\microsoft.extensions.configuration\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.Extensions.Configuration.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.extensions.configuration.abstractions\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.Extensions.Configuration.Abstractions.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.extensions.configuration.binder\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.Extensions.Configuration.Binder.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.extensions.dependencyinjection\3.0.0-preview9.19423.4\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\3.0.0-preview9.19423.4\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.extensions.logging\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.Extensions.Logging.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.extensions.logging.abstractions\3.0.0-preview9.19423.4\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.extensions.options\3.0.0-preview9.19423.4\lib\netstandard2.0\Microsoft.Extensions.Options.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.extensions.primitives\3.0.0-preview9.19423.4\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll" -a "C:\Users\xxx\.nuget\packages\microsoft.jsinterop\3.0.0-preview9.19423.4\lib\netstandard2.0\Microsoft.JSInterop.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.net.http.headers\2.2.0\lib\netstandard2.0\Microsoft.Net.Http.Headers.dll" -a "C:\Users\xxx\.nuget\packages\mono.webassembly.interop\3.0.0-preview9.19423.4\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "C:\Users\xxx\.nuget\packages\newtonsoft.json\12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll" -a "C:\Users\xxx\.nuget\packages\system.buffers\4.5.0\lib\netstandard2.0\System.Buffers.dll" -a "C:\Users\xxx\.nuget\packages\system.componentmodel.annotations\4.6.0-preview9.19421.4\lib\netstandard2.0\System.ComponentModel.Annotations.dll" -a "C:\Users\xxx\.nuget\packages\system.memory\4.5.3\lib\netstandard2.0\System.Memory.dll" -a "C:\Users\xxx\.nuget\packages\system.numerics.vectors\4.5.0\lib\netstandard2.0\System.Numerics.Vectors.dll" -a "C:\Users\xxx\.nuget\packages\system.runtime.compilerservices.unsafe\4.6.0-preview9.19421.4\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll" -a "C:\Users\xxx\.nuget\packages\system.text.encodings.web\4.6.0-preview9.19421.4\lib\netstandard2.0\System.Text.Encodings.Web.dll" -a "C:\Users\xxx\.nuget\packages\system.text.json\4.6.0-preview9.19421.4\lib\netstandard2.0\System.Text.Json.dll" -a "C:\Users\xxx\.nuget\packages\system.threading.tasks.extensions\4.5.2\lib\netstandard2.0\System.Threading.Tasks.Extensions.dll" -a exited with code -532462766.
4>Done building project "Multibet.Logs.Ui.WebBlazor.csproj" -- FAILED.
```

**Comment by chucker** [comment]
You probably need to wait for #38.
